apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-fastapi-app
  template:
    metadata:
      labels:
        app: iris-fastapi-app
    spec:
      containers:
      - name: iris-fastapi-app
        image: us-central1-docker.pkg.dev/tough-study-473007-a5/artifacts-repo-mlops/iris-fastapi-app:latest
        ports:
        - containerPort: 8000

